"""Markdown + JSON report writers."""

from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable, List, Optional

from .cases import CaseResult


STATUS_BADGE = {
    "pass": "PASS",
    "fail": "FAIL",
    "info": "INFO",
    "skip": "SKIP",
    "error": "ERROR",
}


def _git_sha() -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], stderr=subprocess.DEVNULL
        )
        return out.decode("utf-8").strip()
    except Exception:
        return ""


def _format_scalar(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        if value == 0 or (abs(value) >= 1.0e-3 and abs(value) < 1.0e6):
            return f"{value:.6g}"
        return f"{value:.3e}"
    if isinstance(value, (dict, list)):
        return f"`{json.dumps(value, sort_keys=True)}`"
    return str(value)


def _summary_counts(results: Iterable[CaseResult]) -> dict:
    counts = {k: 0 for k in STATUS_BADGE}
    counts["total"] = 0
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1
        counts["total"] += 1
    return counts


def write_report(
    results: List[CaseResult],
    markdown_path: Path,
    json_path: Optional[Path] = None,
    *,
    runs_dir: Optional[Path] = None,
) -> None:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    counts = _summary_counts(results)
    git_sha = _git_sha()

    lines: List[str] = []
    lines.append("# TRECH validation report")
    lines.append("")
    lines.append(
        "Generated by `python -m trech_validation` on a TRECH run output set. "
        "Each row is a physics-consistency check; the table is alphabetised so "
        "`git diff` between commits shows clean regression/improvement deltas."
    )
    lines.append("")
    lines.append("## Run metadata")
    lines.append("")
    lines.append(f"- generated_at_utc: `{timestamp}`")
    if git_sha:
        lines.append(f"- git_sha: `{git_sha}`")
    if runs_dir is not None:
        lines.append(f"- runs_dir: `{runs_dir}`")
    lines.append(
        f"- counts: total={counts['total']}, "
        f"pass={counts['pass']}, fail={counts['fail']}, "
        f"info={counts['info']}, skip={counts['skip']}, error={counts['error']}"
    )
    lines.append("")
    lines.append("## Summary table")
    lines.append("")
    lines.append("| Status | Case | Category | Measured | Expected | Delta | Summary |")
    lines.append("|--------|------|----------|----------|----------|-------|---------|")
    for r in results:
        lines.append(
            "| {status} | `{name}` | {category} | {measured} | {expected} | {delta} | {summary} |".format(
                status=STATUS_BADGE.get(r.status, r.status),
                name=r.name,
                category=r.category,
                measured=_format_scalar(r.measured),
                expected=_format_scalar(r.expected),
                delta=_format_scalar(r.delta),
                summary=r.summary.replace("|", "\\|"),
            )
        )
    lines.append("")
    lines.append("## Cases")
    lines.append("")
    for r in results:
        lines.append(f"### `{r.name}`  ·  {STATUS_BADGE.get(r.status, r.status)}")
        lines.append("")
        lines.append(f"- category: `{r.category}`")
        lines.append(f"- description: {r.description}")
        lines.append(f"- summary: {r.summary}")
        if r.references:
            lines.append("- references:")
            for ref in r.references:
                lines.append(f"  - {ref}")
        if r.tolerance is not None:
            lines.append(f"- tolerance: {_format_scalar(r.tolerance)}")
        if r.notes:
            lines.append("- notes:")
            for note in r.notes:
                lines.append(f"  - {note}")
        lines.append("")

    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    if json_path is not None:
        payload = {
            "schema": "trech_validation_report_v1",
            "generated_at_utc": timestamp,
            "git_sha": git_sha,
            "runs_dir": str(runs_dir) if runs_dir is not None else "",
            "counts": counts,
            "results": [r.to_dict() for r in results],
        }
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n",
                             encoding="utf-8")
